### ISSUE TITLE
Weekly Scrum - March 12th 2021

### ISSUE THREAD

**Issue by Mathew0876** [GabrielCiolac/SYSC4806#34]
- what have I done this week? (with link(s) to the relevant GitHub Issue(s))

- what will I do next week? (with link(s) to the relevant GitHub Issue(s))

- what is holding me back? (if applicable)

**Comment by Mathew0876** [comment]
Work completed this week: 
Issue #20 - Set up rest service for form creation
Issue #21 - Set up rest controllers for adding questions to form

**Comment by sammytripp** [comment]
Work completed this week:
Issue #15 - Set up FormController for displaying form master list
Issue #18 - Create HTML page which serves master list of forms

**Comment by GabrielCiolac** [comment]
Closed:
Issue #13 #14 regarding repo

Will work on:
Issues #42 #39
