### ISSUE TITLE
Weekly Scrum- March 14th 2021 

### ISSUE THREAD

**Issue by thatSoftwareGirl** [GabrielCiolac/SYSC4806#53]
- what have I done this week? (with link(s) to the relevant GitHub Issue(s))
 
- what will I do next week? (with link(s) to the relevant GitHub Issue(s))

- what is holding me back? (if applicable)

**Comment by GabrielCiolac** [comment]
- Started work on #42 
- Continue work on #42

**Comment by thatSoftwareGirl** [comment]
What have I done 
- Started #55 

What will I do next week 
- Continue #55 

What is holding me back
-My other courses
