### ISSUE TITLE
Weekly Scrum - March 21st, 2021 - March 27th, 2021

### ISSUE THREAD

**Issue by thatSoftwareGirl** [GabrielCiolac/SYSC4806#59]
- what have I done this week? (with link(s) to the relevant GitHub Issue(s))

- what will I do next week? (with link(s) to the relevant GitHub Issue(s))

- what is holding me back? (if applicable)

**Comment by GabrielCiolac** [comment]
- Finished Issue #42
- Started work #63

**Comment by Mathew0876** [comment]
Worked on Issue #40 to create front end for the form with ajax, will work on responses to survey questions next week

**Comment by thatSoftwareGirl** [comment]
Continue working on #55

Will work on response next week for rating question next week

**Comment by sammytripp** [comment]
What have I done this 

- Issue #69 Open Ended Question
- Issue #70 Error Page

Next week:
- Assisting with response formatting, and other UI improvements
